        // Countries with flags and hints - CORRECTED VERSION
        this.countries = {
            easy: [
                { name: 'USA', flag: '🇺🇸', hint: 'Land of the free, home of the brave' },
                { name: 'CANADA', flag: '🇨🇦', hint: 'Known for maple syrup and hockey' },
                { name: 'JAPAN', flag: '🇯🇵', hint: 'Land of the rising sun' },
                { name: 'FRANCE', flag: '🇫🇷', hint: 'Famous for the Eiffel Tower' },
                { name: 'ITALY', flag: '🇮🇹', hint: 'Boot-shaped country, famous for pizza' },
                { name: 'CHINA', flag: '🇨🇳', hint: 'Has the Great Wall' },
                { name: 'SPAIN', flag: '🇪🇸', hint: 'Famous for flamenco dancing' },
                { name: 'EGYPT', flag: '🇪🇬', hint: 'Home to ancient pyramids' },
                { name: 'BRAZIL', flag: '🇧🇷', hint: 'Largest country in South America' },
                { name: 'INDIA', flag: '🇮🇳', hint: 'Home to the Taj Mahal' },
                { name: 'GERMANY', flag: '🇩🇪', hint: 'Known for cars and Oktoberfest' },
                { name: 'RUSSIA', flag: '🇷🇺', hint: 'Largest country in the world' },
                { name: 'MEXICO', flag: '🇲🇽', hint: 'Famous for tacos and sombreros' },
                { name: 'UNITED KINGDOM', flag: '🇬🇧', hint: 'Island nation with Big Ben' },
                { name: 'SOUTH KOREA', flag: '🇰🇷', hint: 'Known for K-pop and kimchi' }
            ],
            medium: [
                { name: 'AUSTRALIA', flag: '🇦🇺', hint: 'Home to kangaroos and koalas' },
                { name: 'GREECE', flag: '🇬🇷', hint: 'Birthplace of democracy and Olympics' },
                { name: 'TURKEY', flag: '🇹🇷', hint: 'Bridge between Europe and Asia' },
                { name: 'THAILAND', flag: '🇹🇭', hint: 'Known for temples and spicy food' },
                { name: 'ARGENTINA', flag: '🇦🇷', hint: 'Famous for tango dancing' },
                { name: 'POLAND', flag: '🇵🇱', hint: 'Heart of Europe with medieval cities' },
                { name: 'CHILE', flag: '🇨🇱', hint: 'Long, narrow country along Pacific coast' },
                { name: 'PERU', flag: '🇵🇪', hint: 'Home to Machu Picchu and llamas' },
                { name: 'COLOMBIA', flag: '🇨🇴', hint: 'Known for coffee and emeralds' },
                { name: 'VIETNAM', flag: '🇻🇳', hint: 'Famous for pho soup and motorcycles' },
                { name: 'PHILIPPINES', flag: '🇵🇭', hint: 'Island nation with over 7,000 islands' },
                { name: 'MOROCCO', flag: '🇲🇦', hint: 'Gateway to Africa with beautiful markets' },
                { name: 'KENYA', flag: '🇰🇪', hint: 'Home to safari animals and Maasai people' },
                { name: 'NIGERIA', flag: '🇳🇬', hint: 'Most populous country in Africa' },
                { name: 'ISRAEL', flag: '🇮🇱', hint: 'Holy land with ancient history' },
                { name: 'INDONESIA', flag: '🇮🇩', hint: 'Largest archipelago in the world' },
                { name: 'MALAYSIA', flag: '🇲🇾', hint: 'Twin towers and tropical rainforests' },
                { name: 'SINGAPORE', flag: '🇸🇬', hint: 'Modern city-state in Southeast Asia' }
            ],
            hard: [
                { name: 'SWITZERLAND', flag: '🇨🇭', hint: 'Neutral country famous for chocolate' },
                { name: 'NETHERLANDS', flag: '🇳🇱', hint: 'Land of tulips and windmills' },
                { name: 'NORWAY', flag: '🇳🇴', hint: 'Land of fjords and northern lights' },
                { name: 'SWEDEN', flag: '🇸🇪', hint: 'Home to IKEA and meatballs' },
                { name: 'PORTUGAL', flag: '🇵🇹', hint: 'Famous for explorers and pastries' },
                { name: 'IRELAND', flag: '🇮🇪', hint: 'Emerald Isle with leprechauns' },
                { name: 'SOUTH AFRICA', flag: '🇿🇦', hint: 'Rainbow Nation at tip of Africa' },
                { name: 'NEW ZEALAND', flag: '🇳🇿', hint: 'Island nation with hobbits and sheep' },
                { name: 'FINLAND', flag: '🇫🇮', hint: 'Land of saunas and Santa Claus' },
                { name: 'DENMARK', flag: '🇩🇰', hint: 'Home of LEGO and fairy tales' },
                { name: 'BELGIUM', flag: '🇧🇪', hint: 'Famous for waffles and chocolate' },
                { name: 'AUSTRIA', flag: '🇦🇹', hint: 'Land of Mozart and the Alps' },
                { name: 'CZECH REPUBLIC', flag: '🇨🇿', hint: 'Heart of Europe with Prague castle' },
                { name: 'HUNGARY', flag: '🇭🇺', hint: 'Known for thermal baths and goulash' },
                { name: 'CROATIA', flag: '🇭🇷', hint: 'Beautiful coastline on Adriatic Sea' },
                { name: 'ROMANIA', flag: '🇷🇴', hint: 'Home to Dracula legend and castles' },
                { name: 'BULGARIA', flag: '🇧🇬', hint: 'Land of roses and yogurt' },
                { name: 'SERBIA', flag: '🇷🇸', hint: 'Crossroads of Central and Balkan Europe' },
                { name: 'SLOVENIA', flag: '🇸🇮', hint: 'Alpine country with emerald river' },
                { name: 'SLOVAKIA', flag: '🇸🇰', hint: 'Mountainous country in Central Europe' },
                { name: 'ESTONIA', flag: '🇪🇪', hint: 'Digital pioneer in Northern Europe' },
                { name: 'LATVIA', flag: '🇱🇻', hint: 'Baltic state with beautiful beaches' },
                { name: 'LITHUANIA', flag: '🇱🇹', hint: 'Southernmost Baltic state' },
                { name: 'ICELAND', flag: '🇮🇸', hint: 'Land of fire and ice with geysers' },
                { name: 'LUXEMBOURG', flag: '🇱🇺', hint: 'Small wealthy country in Europe' },
                { name: 'BANGLADESH', flag: '🇧🇩', hint: 'Land of rivers and Bengal tigers' },
                { name: 'PAKISTAN', flag: '🇵🇰', hint: 'Land of the pure with high mountains' },
                { name: 'NEPAL', flag: '🇳🇵', hint: 'Home to Mount Everest' },
                { name: 'SRI LANKA', flag: '🇱🇰', hint: 'Pearl of the Indian Ocean' },
                { name: 'MYANMAR', flag: '🇲🇲', hint: 'Land of golden pagodas' },
                { name: 'CAMBODIA', flag: '🇰🇭', hint: 'Home to ancient Angkor Wat' },
                { name: 'LAOS', flag: '🇱🇦', hint: 'Landlocked country in Southeast Asia' },
                { name: 'MONGOLIA', flag: '🇲🇳', hint: 'Land of nomads and vast steppes' },
                { name: 'KAZAKHSTAN', flag: '🇰🇿', hint: 'Largest landlocked country' },
                { name: 'UZBEKISTAN', flag: '🇺🇿', hint: 'Heart of the Silk Road' },
                { name: 'GEORGIA', flag: '🇬🇪', hint: 'Crossroads of Europe and Asia' },
                { name: 'ARMENIA', flag: '🇦🇲', hint: 'First Christian nation in the world' },
                { name: 'AZERBAIJAN', flag: '🇦🇿', hint: 'Land of fire with oil reserves' },
                { name: 'JORDAN', flag: '🇯🇴', hint: 'Desert kingdom with Petra ruins' },
                { name: 'LEBANON', flag: '🇱🇧', hint: 'Cedar country in the Middle East' },
                { name: 'UAE', flag: '🇦🇪', hint: 'Modern desert oasis with tall buildings' },
                { name: 'QATAR', flag: '🇶🇦', hint: 'Rich peninsula nation' },
                { name: 'SAUDI ARABIA', flag: '🇸🇦', hint: 'Birthplace of Islam with vast deserts' },
                { name: 'UKRAINE', flag: '🇺🇦', hint: 'Largest country entirely in Europe' },
                { name: 'BELARUS', flag: '🇧🇾', hint: 'Land of forests and lakes' }
            ]
        };